import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import axios from 'axios';

import { useState, useEffect } from 'react';
import { authenticateToken } from '../middleware/tokenAuthenticate';

export default function Home() {

  useEffect(() => {

    const getCurrentUser = () => {
      axios.get('/api/user/current')
        .then((response) => { 
          const {data: {user}} = response;
  
          if (user._id) { //user is logged in
            
            localStorage.setItem('token', user.accessToken);
            console.log('login successful')
  
          } else { //user is not logged in
            console.log('user not logged in')
            checkToken();
          }
        })
        .catch(err => {
          console.error(err)
        })
    }

    const checkToken = () => {
      const token = localStorage.getItem('token');
      if (token) {
        try {
          axios.get('/api/user/token', {
            headers: {
              'Authorization': "Bearer " + token
            }
          })
            .then(response => {
              console.log(response)
            })
        } catch (err) {
          console.log('invalid token')
        }
      }
    }

    getCurrentUser();
    
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form action="/api/user/login" method="post">
        <input type="email" name="email" autoComplete="on" placeholder="Email"/>
        <input type="password" name="password" autoComplete="on" placeholder="Password" />
        <button type="submit">Submit</button>
      </form>
    </div>
  )
}
